### ISSUE TITLE
Latest version of ocf does not build with SPDK 21.04

### ISSUE THREAD

**Issue by smijolovic** [Open-CAS/ocf#498]
On Ubuntu 20.04.2:

./configure --enable-debug --enable-werror --disable-unit-tests --disable-examples --enable-ubsan --with-dpdk=$SPDK_SOURCE/dpdk-$BUILD_DPDK_RELEASE/dpdk/build --with-virtio --with-isal --with-iscsi-initiator --with-rdma --with-uring=$SPDK_SOURCE/liburing-$BUILD_LIBURING_RELEASE/liburing/spdk/ --with-fuse --with-crypto --with-pmdk --with-reduce --with-shared --with-ocf

make all  

...
CC app/nvmf_tgt/nvmf_main.o
  LINK nvmf_tgt
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(metadata_io.o): in function `metadata_io_req_finalize':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/metadata/metadata_io.c:317: undefined reference to `env_mpool_del'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(metadata_io.o): in function `metadata_io_i_asynch':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/metadata/metadata_io.c:398: undefined reference to `env_mpool_new'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/metadata/metadata_io.c:447: undefined reference to `env_mpool_del'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/metadata/metadata_io.c:455: undefined reference to `env_mpool_del'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(metadata_io.o): in function `ocf_metadata_io_ctx_init':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/metadata/metadata_io.c:490: undefined reference to `env_mpool_create'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(metadata_io.o): in function `ocf_metadata_io_ctx_deinit':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/metadata/metadata_io.c:504: undefined reference to `env_mpool_destroy'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(ocf_request.o): in function `ocf_req_allocator_init':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/ocf_request.c:48: undefined reference to `env_mpool_create'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(ocf_request.o): in function `ocf_req_allocator_deinit':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/ocf_request.c:60: undefined reference to `env_mpool_destroy'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(ocf_request.o): in function `ocf_req_new':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/ocf_request.c:82: undefined reference to `env_mpool_new'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/ocf_request.c:85: undefined reference to `env_mpool_new'
/usr/bin/ld.bfd: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/lib/libspdk_ocfenv.a(ocf_request.o): in function `ocf_req_put':
/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/lib/env_ocf/src/ocf/ocf_request.c:214: undefined reference to `env_mpool_del'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/mk/spdk.app.mk:67: /home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/build/bin/nvmf_tgt] Error 1
make[1]: *** [/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/mk/spdk.subdirs.mk:44: nvmf_tgt] Error 2
make: *** [/home/chaasmadmin/nimbus8/spdk/spdk-chaasm-21.04/github.com/spdk/spdk/spdk/mk/spdk.subdirs.mk:44: app] Error 2
Make for spdk failed.

Make builds successfully when pulling spdk ocf submodule 20.12.2

**Comment by mmichal10** [comment]
Hi @smijolovic 

we are working on it. There is a currently [open pull request](https://review.spdk.io/gerrit/c/spdk/spdk/+/7774) which allows using the latest OCF in SPDK. I will let you know as soon as we will resolve all the issues and the patch will be integrated.
