### ISSUE TITLE
Unknown type error when building ocf spdk bdev

### ISSUE THREAD

**Issue by KariukiJ** [Open-CAS/ocf#72]
Hello
I am getting the following error when I try to build SPDK with ocf (--with-ocf option). I have tried to build with the ocf module in SPDK and also downloading the framework from the ocf git repository and I got the same error for both. I also did a build with ocf 18.12 as suggested in one of the other issues posted here and got the same error.

In file included from src/ocf/cleaning/nop.c:7:0:
src/ocf/cleaning/nop.h:12:55: error: unknown type name ‘ocf_cleaner_end_t’; did you mean ‘ocf_cleaner_t’?
 void cleaning_nop_perform_cleaning(ocf_cache_t cache, ocf_cleaner_end_t cmpl);
                                                       ^~~~~~~~~~~~~~~~~
                                                       ocf_cleaner_t
src/ocf/cleaning/nop.c:10:55: error: unknown type name ‘ocf_cleaner_end_t’; did you mean ‘ocf_cleaner_t’?
 void cleaning_nop_perform_cleaning(ocf_cache_t cache, ocf_cleaner_end_t cmpl)
                                                       ^~~~~~~~~~~~~~~~~
                                                       ocf_cleaner_t
/home/john/spdk/mk/spdk.common.mk:330: recipe for target 'src/ocf/cleaning/nop.o' failed
make[3]: *** [src/ocf/cleaning/nop.o] Error 1
/home/john/spdk/mk/spdk.subdirs.mk:44: recipe for target 'ocf/env' failed
make[2]: *** [ocf/env] Error 2
/home/john/spdk/mk/spdk.subdirs.mk:44: recipe for target 'bdev' failed
make[1]: *** [bdev] Error 2
/home/john/spdk/mk/spdk.subdirs.mk:44: recipe for target 'lib' failed
make: *** [lib] Error 2

CC lib/bdev/ocf/env/src/ocf/cleaning/nop.o                                                                      In file included from src/ocf/cleaning/nop.c:7:0:                                                                 src/ocf/cleaning/nop.h:12:55: error: unknown type name ‘ocf_cleaner_end_t’; did you mean ‘ocf_cleaner_t’?          void cleaning_nop_perform_cleaning(ocf_cache_t cache, ocf_cleaner_end_t cmpl);                                                                                          ^~~~~~~~~~~~~~~~~                                                                                                 ocf_cleaner_t                                              src/ocf/cleaning/nop.c:10:55: error: unknown type name ‘ocf_cleaner_end_t’; did you mean ‘ocf_cleaner_t’?          void cleaning_nop_perform_cleaning(ocf_cache_t cache, ocf_cleaner_end_t cmpl)                                                                                           ^~~~~~~~~~~~~~~~~                                                                                                 ocf_cleaner_t                                              /home/john/spdk/mk/spdk.common.mk:330: recipe for target 'src/ocf/cleaning/nop.o' failed                          make[3]: *** [src/ocf/cleaning/nop.o] Error 1                                                                     /home/john/spdk/mk/spdk.subdirs.mk:44: recipe for target 'ocf/env' failed                                         make[2]: *** [ocf/env] Error 2                                                                                    /home/john/spdk/mk/spdk.subdirs.mk:44: recipe for target 'bdev' failed                                            make[1]: *** [bdev] Error 2                                                                                       /home/john/spdk/mk/spdk.subdirs.mk:44: recipe for target 'lib' failed                                             make: *** [lib] Error 2
--

**Comment by mmichal10** [comment]
Could you please provide SPDK and OCF commit ids, for which this error occurs? Also more information about the way you build would be useful.

**Comment by michalwy** [comment]
@KariukiJ - Is it still an issue? If yes, could you provide details that @mmichal10 is asking for?

**Comment by KariukiJ** [comment]
Michal,
I got tied up with other items but will get back to this next week.
